// /* eslint-disable */
// // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-2",
//     "aws_appsync_graphqlEndpoint": "https://o7hek2yw45dtxgepmf6pvtoztm.appsync-api.us-east-2.amazonaws.com/graphql",
//     "aws_appsync_region": "us-east-2",
//     "aws_appsync_authenticationType": "API_KEY",
//     "aws_appsync_apiKey": "da2-atxww7ax5bfsxa2ptfcsrjxnui"
// };


// export default awsmobile;
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

interface AwsMobile {
    aws_project_region: string;
    aws_appsync_graphqlEndpoint: string;
    aws_appsync_region: string;
    aws_appsync_authenticationType: string;
    aws_appsync_apiKey: string;
}

const awsmobile: AwsMobile = {
    aws_project_region: "us-east-2",
    aws_appsync_graphqlEndpoint: "https://o7hek2yw45dtxgepmf6pvtoztm.appsync-api.us-east-2.amazonaws.com/graphql",
    aws_appsync_region: "us-east-2",
    aws_appsync_authenticationType: "API_KEY",
    aws_appsync_apiKey: "da2-atxww7ax5bfsxa2ptfcsrjxnui"
};

export default awsmobile;
``